### ISSUE TITLE
Deleting a group when it has a scheduled message breaks

### ISSUE THREAD

**Issue by afomera** [king601/MessageMe#5]
If you delete a group when there is a scheduled message, it breaks.

**Comment by nynhex** [comment]
This is expected behavior because the scheduled message uses a group.  If you delete the group and there are scheduled messages you have orphaned records which will definitely cause this to break.

Thought on this.  When deleting the group you could also set it to delete the scheduled messages that are queued.  This would solve the problem.

**Comment by afomera** [comment]
Well, here in lies a problem because if you delete a group when it has a scheduled message we'll loose the record of the scheduled message being sent, right?
